version: '3'

services:

  db:
    image: postgres

  rabbit1:
    image: rabbitmq
    ports:
      - "5672:5672"

  web:
    build: ..
    command: python manage.py runserver --settings=config.settings.local 0.0.0.0:8000
    volumes:
      - .:/core
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbit1
    env_file:
      - .env

  celery:
    build: ..
    command: sh -c "sleep 10 && celery -A config worker -l info"
    volumes:
      - .:/core
    depends_on:
      - db
      - rabbit1
    env_file:
      - .env

  celery-beat:
    build: ..
    command: celery -A config beat -l info
    volumes:
      - .:/core
    depends_on:
      - db
      - rabbit1
    env_file:
      - .env
