version: '3'

services:

  db:
    image: postgres

  rabbit1:
    image: rabbitmq
    ports:
      - 5672:5672

  web:
    build: ..
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/core
      - static_volume:/core/static_base
    expose:
      - 8000
    depends_on:
      - db
      - rabbit1
    env_file:
      - .env

  nginx:
    build: ../nginx
    volumes:
      - static_volume:/core/static_base
    ports:
      - 80:80
    depends_on:
      - web

  celery:
    build: ..
    command: sh -c "sleep 10 && celery -A config worker -l info"
    volumes:
      - .:/core
    depends_on:
      - db
      - rabbit1
    env_file:
      - .env

  celery-beat:
    build: ..
    command: celery -A config beat -l info
    volumes:
      - .:/core
    depends_on:
      - db
      - rabbit1
    env_file:
      - .env

volumes:
  static_volume:
