version: '3.3'

services:

  db:
    image: postgres
    volumes:
      - .:/core
    env_file:
      - ../envs/.env
    ports:
      - "5432:5432"

  rabbit1:
    image: rabbitmq
    ports:
      - "5672:5672"

  celery:
    build: ..
    command: sh -c "sleep 10 && celery -A config worker -l info"
    volumes:
      - .:/core
    depends_on:
      - db
      - rabbit1
    env_file:
      - ../envs/.env

  celery-beat:
    build: ..
    command: celery -A config beat -l info
    volumes:
      - .:/core
    depends_on:
      - db
      - rabbit1
    env_file:
      - ../envs/.env

volumes:
  static_volume:
