# Generated by Django 2.2.9 on 2020-02-27 07:00

import uuid

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='time start')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='time end')),
                ('round_game', models.CharField(choices=[('I', 'First round'), ('II', 'Second round'), ('III', 'Third round'), ('IV', 'Fourth round'), ('25', 'Loser 25 place game'), ('17', 'Loser 17 place game'), ('13', 'Loser 13 place game'), ('9', 'Loser 9 place game'), ('7', 'Loser 7 place game'), ('5', 'Loser 5 place game'), ('SF', 'Semi-final game'), ('3/4', 'Game 3/4 places'), ('F', 'Final game')], max_length=3, verbose_name='round')),
                ('game_number', models.IntegerField(verbose_name='number of the game')),
                ('court_number', models.IntegerField(blank=True, null=True, verbose_name='court number')),
                ('home_team_score', models.IntegerField(blank=True, null=True, verbose_name='home team score')),
                ('away_team_score', models.IntegerField(blank=True, null=True, verbose_name='away team score')),
                ('winner_ref', models.CharField(blank=True, max_length=3, null=True, verbose_name='winner reference game number')),
                ('loser_ref', models.CharField(blank=True, max_length=3, null=True, verbose_name='loser reference game number')),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
