# Generated by Django 2.2.9 on 2020-01-30 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0002_auto_20200130_2132'),
        ('game', '0001_initial'),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='participant.Team', verbose_name='team which plays visiting'),
        ),
        migrations.AddField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Competition', verbose_name='competition'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='participant.Team', verbose_name='team which plays at home'),
        ),
    ]
