# Generated by Django 2.2.9 on 2020-02-27 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("participant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referee",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="rating",
            field=models.ManyToManyField(
                blank=True,
                related_name="players",
                to="participant.Rating",
                verbose_name="rating",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ManyToManyField(
                blank=True,
                related_name="players",
                to="participant.Team",
                verbose_name="team",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
